language: shell
os: windows
env:
  - MSBUILD_PATH="c:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
install:
  - export PATH=$MSBUILD_PATH:$PATH
  - export JAVA_HOME=${JAVA_HOME:-/c/jdk}
  - export PATH=${JAVA_HOME}/bin:${PATH}
  - choco install jdk8 -params 'installdir=c:\\jdk' -y
script:
  - ./gradlew build
  - ./build_dll.sh